apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-application-chart.fullname" . }}
  labels:
    {{- include "generic-application-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "generic-application-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "generic-application-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic-application-chart.serviceAccountName" . }}
      securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
      initContainers:
      {{ if .Values.gitRepoConfig.url }}

      - name: init-config-container-git
        image: baltig.infn.it:4567/epics-containers/container-init 
        env:
          {{- if .Values.http_proxy }}
          - name: HTTP_PROXY
            value: {{.Values.http_proxy | quote}} 
          {{- end}}
          {{- if .Values.https_proxy }}
          - name: HTTPS_PROXY
            value: {{.Values.https_proxy | quote}} 
          {{- end}}
          {{- if .Values.no_proxy }}
          - name: NO_PROXY
            value: {{.Values.no_proxy | quote}} 
          {{- end}}

        command: 
        - sh 
        - -c
        - |
          id=`id`
          cd /tmp
          ls -latr
          echo "ID $id repository {{ .Values.gitRepoConfig.url }} path: {{ .Values.gitRepoConfig.path}} "
          if [ -d temp-config ];then
            rm -rf temp-config
          fi
          # Cloning logic with PAT
          if [ -n "{{ .Values.gitRepoConfig.token }}" ]; then
            echo "Cloning repository using Personal Access Token"
            if [ -n "{{ .Values.gitRepoConfig.branch }}" ]; then
              git clone -b {{ .Values.gitRepoConfig.branch }} https://oauth2:{{ .Values.gitRepoConfig.token }}@{{ .Values.gitRepoConfig.url | replace "https://" "" }} --recurse-submodules temp-config
            else
              git clone https://oauth2:{{ .Values.gitRepoConfig.token }}@{{ .Values.gitRepoConfig.url | replace "https://" "" }} --recurse-submodules temp-config
            fi
          else
            echo "Cloning repository unauthenticated"
            if [ -n "{{ .Values.gitRepoConfig.branch }}" ]; then
              git clone -b {{ .Values.gitRepoConfig.branch }} {{ .Values.gitRepoConfig.url }} --recurse-submodules temp-config
            else
              git clone {{ .Values.gitRepoConfig.url }} --recurse-submodules temp-config
            fi
          fi
          
          if [ -d temp-config/{{ .Values.gitRepoConfig.path}} ];then
            if [ "{{ .Values.gitRepoConfig.path }}" == "." ];then
                mv temp-config/* /tmp/
            else
              mv temp-config/{{ .Values.gitRepoConfig.path}}/* /tmp/
              rm -rf temp-config
            fi
          else
            mv temp-config/* /tmp/
          fi

          ls /tmp
          {{- if .Values.gitRepoConfig.exec }}
          {{ .Values.gitRepoConfig.exec }}
          {{- end }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /tmp
    {{ end }}
    {{ if .Values.gitRepoApp.url }}
      - name: init-app-container-git
        image: baltig.infn.it:4567/epics-containers/container-init  
        env:
        {{- if .Values.http_proxy }}
        - name: HTTP_PROXY
          value: {{.Values.http_proxy | quote}} 
        {{- end}}
        {{- if .Values.https_proxy }}
        - name: HTTPS_PROXY
          value: {{.Values.https_proxy | quote}} 
        {{- end}}
        {{- if .Values.no_proxy }}
        - name: NO_PROXY
          value: {{.Values.no_proxy | quote}} 
        {{- end}}

        command:
        - sh 
        - -c
        - |
          id=`id`
          cd /tmp
          ls -latr
          echo "ID $id repository {{ .Values.gitRepoApp.url }} "
          # Cloning logic with PAT
          if [ -d temp-config ];then
            rm -rf temp-config
          fi
          if [ -n "{{ .Values.gitRepoApp.token }}" ]; then
            echo "Cloning repository using Personal Access Token"
            if [ -n "{{ .Values.gitRepoApp.branch }}" ]; then
              git clone -b {{ .Values.gitRepoApp.branch }} https://oauth2:{{ .Values.gitRepoApp.token }}@{{ .Values.gitRepoApp.url | replace "https://" "" }} --recurse-submodules temp-config
            else
              git clone https://oauth2:{{ .Values.gitRepoApp.token }}@{{ .Values.gitRepoApp.url | replace "https://" "" }} --recurse-submodules temp-config
            fi
          else
            echo "Cloning repository unauthenticated"
            if [ -n "{{ .Values.gitRepoApp.branch }}" ]; then
              git clone -b {{ .Values.gitRepoApp.branch }} {{ .Values.gitRepoApp.url }} --recurse-submodules temp-config
            else
              git clone {{ .Values.gitRepoApp.url }} --recurse-submodules temp-config
            fi
          fi
          if [ -n "{{ .Values.gitRepoApp.branch }}" ];then
            git clone -b {{ .Values.gitRepoApp.branch }} {{ .Values.gitRepoApp.url }} --recurse-submodules temp-config
          else
            git clone {{ .Values.gitRepoApp.url }} --recurse-submodules temp-config
          fi

          if [ -d temp-config/{{ .Values.gitRepoApp.path}} ];then
            if [ "{{ .Values.gitRepoApp.path }}" == "." ];then
                mv temp-config/* /tmp/
            else
              mv temp-config/{{ .Values.gitRepoApp.path}}/* /tmp/
              rm -rf temp-config
            fi
          else
            mv temp-config/* /tmp/
          fi

          # chmod a+w,a+r -R /tmp
          ls /tmp
          {{- if .Values.gitRepoApp.exec }}
          {{ .Values.gitRepoApp.exec }}
          {{- end }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: app-volume
          mountPath: /tmp
    
    {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.http_proxy }}
          - name: HTTP_PROXY
            value: {{.Values.http_proxy | quote}} 
          {{- end}}
          {{- if .Values.https_proxy }}
          - name: HTTPS_PROXY
            value: {{.Values.https_proxy | quote}} 
          {{- end}}
          {{- if .Values.no_proxy }}
          - name: NO_PROXY
            value: {{.Values.no_proxy | quote}} 
          {{- end}}
          {{- if .Values.exec }}
          command: 
            - sh 
            - -c
            - |
              cd /app
              {{ .Values.exec }}
          {{- end }}
          volumeMounts:

          {{- if .Values.gitRepoApp.url}}
            - name: app-volume
              mountPath: /app
          {{- end}}
          {{- if .Values.gitRepoConfig.url }}
            - name: config-volume
              mountPath: /config
          {{- end}}
          ports:
          {{- range .Values.service.ports }}
            - name: {{ .targetname }}
              containerPort: {{.targetport}}
              protocol: {{.protocol}}
          {{- end }}
          
          resources:
{{ toYaml .Values.resources | indent 12}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.gitRepoConfig.url}}
        - name: config-volume
          persistentVolumeClaim:
            claimName: {{ include "generic-application-chart.fullname" . }}-config
      {{- end }}
      {{- if .Values.gitRepoApp.url}}
        - name: app-volume
          persistentVolumeClaim:
            claimName: {{ include "generic-application-chart.fullname" . }}-app
      {{- end }}
