apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-application-chart.fullname" . }}
  labels:
    {{- include "generic-application-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end}}
  selector:
    {{- include "generic-application-chart.selectorLabels" . | nindent 4 }}
