{{- if .Values.service.ports }}
{{- if gt (len .Values.service.ports) 0 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-application-chart.fullname" . }}
  labels:
    {{- include "generic-application-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.staticIP }}
  clusterIP: {{.Values.staticIP}}
  {{- end }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetport }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "generic-application-chart.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
